name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm ci
      - name: Check code formatting (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run format:check
      - name: Install Playwright Browsers (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx playwright install --with-deps
      - name: Run Playwright tests (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run test
      - name: Update Service Worker Version
        run: |
          # Generate human-readable version using current date and time in Europe/Stockholm timezone
          VERSION=$(TZ=Europe/Stockholm date +"%y%m%d.%H%M")
          echo "Updating service worker version to: $VERSION"
          # Update the version in sw.js
          sed -i "s/let version = \".*\";/let version = \"$VERSION\";/" src/sw.js
          # Verify the change
          grep "let version" src/sw.js
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0F08C3A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./src" # App source code path
          skip_app_build: true
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0F08C3A03 }}
          action: "close"
