name: Code Quality Checks

on:
  push:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Check Code Formatting
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check Prettier formatting
        run: |
          echo "🔍 Checking code formatting with Prettier..."
          if ! npm run format:check; then
            echo ""
            echo "❌ Code formatting issues found!"
            echo ""
            echo "To fix formatting issues, run:"
            echo "  npm run format"
            echo ""
            echo "Or in PowerShell:"
            echo "  npm run format"
            echo ""
            exit 1
          fi
          echo "✅ All files are properly formatted!"