name: PR Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests on PR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
        
      - name: Run Playwright tests
        run: npm run test
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-pr
          path: playwright-report/
          retention-days: 7
          
      - name: Comment PR with test results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            let testResults = '🧪 **Playwright Test Results**\n\n';
            
            try {
              // Try to read the results
              const reportPath = path.join(process.cwd(), 'test-results');
              if (fs.existsSync(reportPath)) {
                testResults += '✅ Tests completed. Check the [test report artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.\n';
              } else {
                testResults += '❓ Test results not found.\n';
              }
            } catch (error) {
              testResults += `❌ Error reading test results: ${error.message}\n`;
            }
            
            testResults += '\n📊 [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: testResults
            });